name: CI Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PORT: 3001
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET: ${{ secrets.S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: |
          nohup node server.js > server.log 2>&1 &
          sleep 10

      - name: Check logs (debug)
        run: cat server.log

      - name: Health check (retry)
        run: |
          for i in {1..5}; do
            curl http://localhost:3001 && exit 0
            echo "Retrying..."
            sleep 3
          done
          exit 1